### ISSUE TITLE
Add monthly rate limits

### ISSUE THREAD

**Issue by spikelu2016** [bricks-cloud/BricksLLM#26]
https://community.openai.com/t/openai-api-proxy-to-share-limited-token-budget-with-others/535403/14

**Comment by spikelu2016** [comment]
@LinqLover we support monthly spend limit now

**Comment by LinqLover** [comment]
Very nice! Would this also work with minutes? Also, monthly cost limits  are not yet combinable with hourly cost limits, are they?

**Comment by spikelu2016** [comment]
> Very nice! Would this also work with minutes? Also, monthly cost limits are not yet combinable with hourly cost limits, are they?

To answer your first question, minutes is not available yet but I can make it available quite easily. For the second question, they are not combinable atm.

**Comment by LinqLover** [comment]
The first one would be great! The second one, too, but not so urgent. :-)

**Comment by spikelu2016** [comment]
> The first one would be great! The second one, too, but not so urgent. :-)

Updated. minute sped limit should be supported in the latest version
