### ISSUE TITLE
Authentication for Key Creation in BricksLLM API

### ISSUE THREAD

**Issue by Elliot-Construct** [bricks-cloud/BricksLLM#42]
Description:
I am using the BricksLLM API to create keys for my application. However, I am concerned about unauthorized key creation. Is there any way to add authentication to the key creation process?

Steps to Reproduce:
1. Navigate to the key creation section of the BricksLLM API.
2. Attempt to create a key without authentication.
3. Observe that the key is created successfully.

Expected Behavior:
Unauthorized key creation should not be possible. There should be some form of authentication required to create a key.

Actual Behavior:
Unauthorized key creation is possible without any authentication.

Additional Information:
I am using the latest version of the BricksLLM API. I have not made any modifications to the API code.

**Comment by spikelu2016** [comment]
This issue is temporarily fixed by https://github.com/bricks-cloud/BricksLLM/commit/afc10cb5b6fe94670b4f60c7e19d43a3e98c0bce
