### ISSUE TITLE
Health Check Endpoints: Documentation and Usage

### ISSUE THREAD

**Issue by avukonkepeter-rain** [bricks-cloud/BricksLLM#68]
Hello World!

So there is currently a health check endpoint available at: 'api/health'

This API is not well documented and it is not clear if it is an internal API or if it safe for use in self-hosted or managed instances of BricksLLM.

If this endpoint is officially supported could it be included in the official documentation and it's use more thoroughly explained: https://docs.trybricks.ai/docs

Also whether this API differs between managed instances and self-hosted instances as in practice I've observed them to behave differently. 

Clarity on the best way to monitor the service is highly valuable for deployments especially to cloud based infrastructure.

**Comment by spikelu2016** [comment]
Got the feedback and added the health check endpoints to the documentation.

**Comment by spikelu2016** [comment]
For monitoring, we offer datadog integration. Do you want a different integration for your use case?

**Comment by kisamoto** [comment]
@spikelu2016 - not OP but if we're talking health integrations it would be nice to have something like a prometheus exporter or OTEL. I use Grafana (specifically Grafana Cloud but could equally be relevant to open-source version) to create dashboards of data so an easy way to get this data there would be beneficial.

I can create a new issue if not relevant to this one.

**Comment by minhoryang** [comment]
Why don't we just use these pipelines with a just simple modification on the BricksLLM?
- [prometheus/statsd_exporter](https://github.com/prometheus/statsd_exporter): convert statsd to prometheus.
- [open-telemetry/opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector)
  - [can receive prometheus metrics](https://opentelemetry.io/docs/collector/configuration/#receivers)
