### ISSUE TITLE
Not able to make it work

### ISSUE THREAD

**Issue by sidharthiimc** [bricks-cloud/BricksLLM#7]
Its it was not able to detect openai api key using export command. I had to update yml file manually. 

![error1](https://github.com/bricks-cloud/BricksLLM/assets/20523129/e60e52c1-0261-4f60-beee-bc50efaf391f)

After updating I am still not able use - Getting following errors: 

{'error': {'message': '[BricksLLM] failed to parse openai error response',
  'code': 500}}

![image](https://github.com/bricks-cloud/BricksLLM/assets/20523129/df096dac-487e-416a-b84e-5abd3d05901d)

**Comment by spikelu2016** [comment]
Thanks for trying out Bricks Sid. Regarding the first issue, if you run `docker-compose up` without sudo. Docker compose should be able to pick up the env variable

**Comment by spikelu2016** [comment]
Full sequence to test the fix
* Pull the latest docker image `docker pull luyuanxin1995/bricksllm:latest`
* Set env variable` export OPENAI_API_KEY=YOUR_KEY`
* Check env variable is correctly set `echo $OPENAI_API_KEY`
* Run docker compose `docker-compose up`
* Create your first API key
* Test the proxy with created Key

You should be able to see something like this if you receive an error from OpenAI
`
{
    "error": {
        "message": "Incorrect API key provided: 1234. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}
`

**Comment by spikelu2016** [comment]
Let me know if you run into additional issues

**Comment by sidharthiimc** [comment]
Thanks for prompt response. For me I can't start docker without sudo. Adding -E in sudo and reverting changes in yml file helped Working end to end now without any update.
