### ISSUE TITLE
Is UI on paid version only?

### ISSUE THREAD

**Issue by slayer** [bricks-cloud/BricksLLM#81]
Hey

UI (Dashboard, stats, etc) will be only in managed version, right?

**Comment by spikelu2016** [comment]
Yes, we also offer self deployment as well. Let me know if you are interested to chat.

**Comment by slayer** [comment]
I've tried to play BricksLLM in order to get stats how much my services spend (desktop apps, browser plugins, my own AI projects, etc), but looks like it's not usable for self deployment since no UI :(

**Comment by spikelu2016** [comment]
Yeah the UI is not free unfortunately
